name:                prairie-sql
version:             0.1.0.0
github:              "parsonsmatt/prairie-sql"
license:             BSD3
author:              "Matt Parsons"
maintainer:          "parsonsmatt@gmail.com"
copyright:           "Matt Parsons"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/parsonsmatt/prairie-sql#readme>

dependencies:
- base >= 4.12 && < 5
- prairie >= 0.0.2.0
- text
- chronos
- bytestring
- vector
- mtl
- lens

default-extensions:
  - DerivingStrategies
  - StandaloneDeriving
  - FlexibleContexts
  - UndecidableInstances
  - GeneralizedNewtypeDeriving
  - BlockArguments
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies
  - TypeOperators
  - TypeApplications
  - ScopedTypeVariables
  - DerivingVia
  - DataKinds
  - StrictData
  - EmptyCase
  - RankNTypes

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  prairie-sql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prairie-sql
    - hspec
    build-tools:
    - hspec-discover
